version: '3.1'

services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile_dev
    image: flask-api:dev
    ports:
    - "8080:8080"
    environment:
    - APISRV_ENV=test
    - DB_CONNECTION=postgresql+psycopg2://postgres:mysecretpassword@db/postgres
    volumes:
    - $PWD/log:/usr/src/flask-api/log
    - $PWD/code:/usr/src/flask-api/code
    depends_on: # lega lo start di un container al running (non ready) di un altro container
      - db
  db:
    image: postgres:12.4-alpine
    ports:
    - "5432:5432"
    volumes:
    - ~/postgresql/data:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=mysecretpassword
    - PGDATA=/var/lib/postgresql/data/pgdata
