version: '3.1'

services:
  flask-api:
    image: flask-api:dev
    ports:
    - "8080:8080"
    environment:
    # you can choose which DB, if you uncomment postgresql, remember to uncomment depends_on section as well
#    - DB_CONNECTION=postgresql+psycopg2://postgres:mysecretpassword@db/postgres
    - DB_CONNECTION=sqlite:///data.db
    volumes:
    - $PWD:/usr/src/flask-api
#    depends_on: # to create a dependency between two containers
#      - db
  db:
    image: postgres:12.4-alpine
    ports:
    - "5432:5432"
    volumes:
    - ~/postgresql/data:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=mysecretpassword
    - PGDATA=/var/lib/postgresql/data/pgdata
